name: Self-hosted runner (nightly-ci)


on:
  repository_dispatch:
  # triggered when the daily scheduled Nvidia CI is completed.
  # This way, we can compare the results more easily.
  workflow_run:
    workflows: ["Self-hosted runner (scheduled)"]
    branches: ["main"]
    types: [completed]
  push:
    branches:
      - fix_nightly_ci

jobs:
  build_nightly_ci_images:
    name: Build CI Docker Images with nightly torch
    uses: ./.github/workflows/build-nightly-ci-docker-images.yml
    secrets: inherit

  model-ci:
    name: Model CI
    # needs: [build_nightly_ci_images]
    uses: ./.github/workflows/self-scheduled.yml
    with:
      job: run_models_gpu
      slack_report_channel: "#transformers-ci-past-future"
      docker: huggingface/transformers-all-latest-torch-nightly-gpu
      ci_event: Nightly CI
      report_repo_id: hf-internal-testing/transformers_daily_ci_with_torch_nightly
      commit_sha: ${{ github.event.workflow_run.head_sha }}
    secrets: inherit
